version: "3.8"
services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
